[formats]
named_fmt = "%d(%F %T) [%M(thread_name)] [%c] %f:%L %U() - %m%n"
csv_format = "%d(%s.%ms),%m%n"

[rules]
client.DEBUG    "log/app.log"; named_fmt
server.DEBUG    "log/app.log"; named_fmt
cc_data.* "cwnd_output.csv"; csv_format
